### ISSUE TITLE
Terms & Conditions page gets open scrolled down to the bottom

### ISSUE THREAD

**Issue by arapulido** [kubeapps/hub#31]
Steps to reproduce:
 
* Open the Hub
* Scroll down to the footer
* Click on Terms and open the Terms in the same tab (not a new tab, not a new window)

Expected results:

* The terms and conditions page opens at the beginning of the page

Actual results:

* The terms and conditions page opens scrolled down to the bottom of the page

**Comment by arapulido** [comment]
Low priority, but we should fix at some point

**Comment by prydonius** [comment]
thanks, should be a quick fix: https://stackoverflow.com/questions/21055952/changing-route-doesnt-scroll-to-top-in-the-new-page

**Comment by Angelmmiguel** [comment]
@prydonius I believe that the fix applies to Angular v1. This is a solution for Angular v2: https://stackoverflow.com/questions/39601026/angular-2-scroll-to-top-on-route-change
