### ISSUE TITLE
Broken link at Source Repository

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/hub#53]
Reference: https://github.com/bitnami/charts/issues/849

Bitnami charts have a broken link in the Source Repository section since the URL is not properly formed. A difference with the other chart repositories is that the Bitnami one has charts in two different folders so the logic to build that URL is not correct.

That section (Source Repository) has been removed in Monocular 1.0 so we should remove that here as well.

cc/ @prydonius

**Comment by arapulido** [comment]
This was already fixed
