### ISSUE TITLE
2 open sessions with the same login can lead to duplicated starring

### ISSUE THREAD

**Issue by arapulido** [kubeapps/hub#7]
Steps to reproduce:

1. Open 2 separate sessions in the Kubeapps Hub (for example, using Firefox and Chrome)
2. Login with the same user on both
3. On each of the sessions, star the same chart
4. Refresh (F5) the page

Expected results:
1. The chart star number increases by 1

Actual results:
1. The chart star number has increased by 2

**Comment by sameersbn** [comment]
The fix has been landed in https://github.com/kubeapps/ratesvc/releases/tag/v0.1.1

**Comment by arapulido** [comment]
Closing as fixed
