### ISSUE TITLE
Change "bitnami" pill color

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/hub#74]
By default, the color of the pill that specifies the repository that hosts a chart is gray. Since we don't have a CSS class for the bitnami repository it's using that gray that doesn't look very good:

![screenshot from 2019-03-07 18-22-06](https://user-images.githubusercontent.com/4025665/53975783-f30f0300-4105-11e9-8544-e2af5173d3d9.png)

**Comment by arapulido** [comment]
This is no longer relevant. We got rid of the pills
