### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by migmartri** [kubeapps/hub#79]
It seems that the installation instructions are not valid for Helm 3

1 - helm install requires passing a name or explicitly setting autogenerate. Also, the --name has been deprecated and the first argument is used as name.

```bash
$ helm install stable/nginx-ingress --version 1.29.5
Error: must either provide a name or specify --generate-name

$ helm install stable/nginx-ingress --version 1.29.5 --name foo
Error: unknown flag: --name
```

2 - The stable repo is not enabled by default. That means that we should show instructions on how to add the repo even for stable/incubator

```bash
$ helm install nginx-ingress  stable/nginx-ingress --namespace nginx --version 1.29.5
Error: failed to download "stable/nginx-ingress" (hint: running `helm repo update` may help)
```

**Comment by andresmgot** [comment]
Thanks for reporting! I have changed that. See for example:

https://hub.kubeapps.com/charts/stable/aerospike

**Comment by migmartri** [comment]
Thanks!
